# -*- coding: utf-8 -*-
"""Tutorial_python_basico.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XFP4hTPpnL2dng9y6GDRYVajMyLrgZGQ

# Primeiro programa em Python
"""

print ("Ola mundo!")

"""# Tipos de Dados

inteiro - int

real - float

caractere - str

texto - str

valor lógico - boolean

# Declaração e atribuição de variáveis
"""

idade: int = 20
salario: float; altura: float
genero: str
nome: str
salario = 5800.5
altura = 1.63
genero = "F"
nome = "Maria Silva"
print(f"IDADE = {idade}")
print(f"SALARIO = {salario:.2f}")
print(f"ALTURA = {altura:.2f}")
print(f"GENERO = {genero}")
print(f"NOME = {nome}")

"""# Operadores aritméticos

adição +

subtração -

multiplicação *

divisão /

resto da divisão ("mod") %

exponenciação **

divisão inteira //

# Operadores comparativos

menor <

maior >

menor ou igual <=

maior ou igual >=

igual ==

diferente != ou <>

# Operadores lógicos

e and

ou or

não not

# Saída de dados
comando print

Placeholder de formatação

int %d

float %f

str %s
"""

print("bom dia", end="")
print("boa noite", end="")

print("bom dia")
print("boa noite")

x: int; y: int
x = 10
y = 20
print(x)
print(y)

x: float
x = 2.3456
print("{:.2f}".format(x))

idade: int
salario: float
nome: str
sexo: str
idade = 32
salario = 4560.9
nome = "Maria Silva"
sexo = "F"
print(f"A funcionaria {nome}, sexo {sexo}, ganha {salario:.2f} e tem {idade} anos")
print("A funcionaria {:s}, sexo {:s}, ganha {:.2f} e tem {:d} anos".format(nome, sexo, salario, idade))

"""# Processamento de dados / Casting"""

x:int; y:int
x = 5
y = 2 * x
print(x)
print(y)

x: int
y: float
x = 5
y = 2 * x
print(x)
print(f"{y:.1f}")

b1: float; b2: float; h: float; area: float
b1 = 6.0
b2 = 8.0
h = 5.0
area = (b1 + b2) / 2.0 * h
print(area)

a: int; b: int; resultado: int
a = 5
b = 2
resultado = a // b
print(resultado)

a: float
b: int
a = 5.0
b = int(a)
print(b)

"""# Entrada de dados"""

salario1: float; salario2: float
nome1: str; nome2: str
idade: int
sexo: str
nome1 = input("Nome da primeira pessoa: ")
salario1 = float(input("Salario da primeira pessoa: "))
nome2 = input("Nome da segunda pessoa: ")
salario2 = float(input("Salario da segunda pessoa: "))
idade = int(input("Digite uma idade: "))
sexo = input("Digite um sexo (F/M): ")
print(f"Nome 1: {nome1}")
print(f"Salario 1: {salario1:.2f}")
print(f"Nome 2: {nome2}")
print(f"Salario 2: {salario2:.2f}")
print(f"Idade: {idade}")
print(f"Sexo: {sexo}")

"""# Estrutura condicional"""

hora: int
hora = int(input("Digite uma hora do dia: "))
if hora < 12:
    print("Bom dia!")
elif hora < 18:
    print("Boa tarde!")
else:
    print("Boa noite!")

"""# Estrutura enquanto"""

x: int
soma: int
soma = 0
x = int(input("Digite o primeiro numero: "))
while x != 0:
    soma = soma + x
    x = int(input("Digite outro numero: "))
print("SOMA = ", soma)

"""# Estrutura para"""

soma: int
N = int(input("Quantos numeros serao digitados? "))
soma = 0
for i in range(0, N):
    x = int(input("Digite um numero: "))
    soma = soma + x
print("SOMA = ", soma)
for i in range(0, N, 2):
    x = int(input("Digite um numero: "))
    soma = soma + x
print("SOMA = ", soma)

"""# Vetores"""

N = int(input("Quantos numeros voce vai digitar? "))
vet: [float] = [0 for x in range(N)]
for i in range(0, N):
    vet[i] = float(input("Digite um numero: "))
print()
print("NUMEROS DIGITADOS:")
for i in range(0, N):
    print(f"{vet[i]:.1f}")

"""# Matrizes"""

N: int
M = int(input("Quantas linhas vai ter a matriz? "))
N = int(input("Quantas colunas vai ter a matriz? "))
mat: [[int]] = [[0 for x in range(N)] for x in range(M)]
for i in range(0, M):
    for j in range(0, N):
        mat[i][j] = int(input(f"Elemento [{i},{j}]: "))
print()
print("MATRIZ DIGITADA:")
for i in range(0, M):
    for j in range(0, N):
        print(f"{mat[i][j]} ", end="")
    print()

"""# Exemplo de código em Python"""

# importando biblioteca
import plotly.express as px # biblioteca para plotar o grafico

# cria uma lista para receber os nomes das linguagens
nomes_linguagens: [str] = [0 for aa in range(28)] 
# carrega os nomes das linguagens
nomes_linguagens = ['Abap', 'Ada', 'C/C++', 'C#', 'Cobol', 'Dart', 'Delphi/Pascal', 'Go', 'Groovy', 'Haskell', 'Java', 'JavaScript', 'Julia', 'Kotlin', 'Lua', 'Matlab', 'Objective-C', 'Perl', 'PHP', 'Python', 'R', 'Ruby', 'Rust', 'Scala', 'Swift', 'TypeScript', 'VBA', 'Visual Basic']

# cria uma lista para receber a media dos valores de cada coluna (linguagem)
media: [float] = [0 for aa in range(28)] 
# carrega os valores da media de uso de cada linguagem
media = [0.52, 0.61, 6.68, 7.03, 0.33, 0.56, 0.07, 1.41, 0.43, 0.25, 17.74, 8.95, 0.35, 1.74, 0.49, 1.55, 2.46, 0.40, 6.25, 30.28, 3.83, 1.07, 0.85, 0.54, 1.76, 1.69, 1.25, 0.69]

# ordena as linguagens pela media em ordem decrescente 
aux_media = 0 # inicializa a variavel auxiliar que vai receber o valor da media temporariamente enquanto troca de lugar as medias que estao fora de ordem
aux_nomes_linguagens = '' # a mesma coisa pra linguagem, para ela acompanhar sua respectiva media

for i in range(0,27): # percorre a lista media uma vez
    for j in range(i, 27): # percorre a lista media novamente comparando os valores 
        if media[i]<media[j]: # se estiver fora de ordem usa a variavel aux para trocar de lugar os valores e colocar na ordem
            aux_media = media[i] # ordena a media
            media[i] = media[j]
            media[j] = aux_media
            aux_nomes_linguagens = nomes_linguagens[i] # faz o nome da linguagem trocar de lugar tambem para acompanhar sua respectiva media
            nomes_linguagens[i] = nomes_linguagens[j]
            nomes_linguagens[j] = aux_nomes_linguagens

# plota no gráfico apenas as 15 primeiras
dados_x=nomes_linguagens[0:15] # pega as linguagens de 0 a 14 - porque a 15 nao entra no fatiamento da lista
dados_y=media[0:15] # pega as medias de 0 a 14 - porque a 15 nao entra no fatiamento da lista

fig = px.pie(names = dados_x, values=dados_y, title=f'As 15 linguagens de programação mais usadas no ano de 2021') # usa o valor da variavel
fig.show() # mostra o grafico